# Generated by Django 4.2.23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(
                help_text='Teacher assigned to this course',
                limit_choices_to={'role': 'teacher'},
                on_delete=django.db.models.deletion.CASCADE,
                to='users.user'
            ),
        ),
    ]