# Generated by Django 4.2.23 on 2025-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20251012_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.CharField(default='TBD', help_text='Assigned classroom (e.g., Room 101, Lab A)', max_length=100),
        ),
    ]
