# Generated by Django 4.2.23 on 2025-10-12 17:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Session title (e.g., 'Lecture 1', 'Lab Session')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional session description')),
                ('classroom_latitude', models.DecimalField(decimal_places=8, help_text='Classroom latitude coordinate', max_digits=10)),
                ('classroom_longitude', models.DecimalField(decimal_places=8, help_text='Classroom longitude coordinate', max_digits=11)),
                ('classroom_name', models.CharField(help_text='Name of the classroom/location', max_length=100)),
                ('allowed_radius', models.PositiveIntegerField(default=50, help_text='Allowed radius in meters for attendance marking', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_duration', models.PositiveIntegerField(default=60, help_text='Scheduled duration in minutes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course for this attendance session', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.course')),
                ('teacher', models.ForeignKey(help_text='Teacher who started this session', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'db_table': 'attendance_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, help_text='Whether student is present')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', help_text='Attendance status', max_length=20)),
                ('student_latitude', models.DecimalField(blank=True, decimal_places=8, help_text="Student's latitude when marking attendance", max_digits=10, null=True)),
                ('student_longitude', models.DecimalField(blank=True, decimal_places=8, help_text="Student's longitude when marking attendance", max_digits=11, null=True)),
                ('location_verified', models.BooleanField(default=False, help_text='Whether location was verified within allowed radius')),
                ('distance_from_classroom', models.FloatField(blank=True, help_text='Distance from classroom in meters', null=True)),
                ('marked_at', models.DateTimeField(blank=True, help_text='When student marked attendance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(help_text='Attendance session', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesession')),
                ('student', models.ForeignKey(help_text='Student who marked attendance', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendances',
                'ordering': ['-marked_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
