# Generated by Django 4.2.23 on 2025-10-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='JWT token for attendance verification', max_length=500, unique=True)),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the token for quick lookup', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether token is still valid')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times token was used')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum allowed uses (0 = unlimited)')),
                ('session', models.ForeignKey(help_text='Attendance session this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Token',
                'verbose_name_plural': 'Attendance Tokens',
                'db_table': 'attendance_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='attendance__token_h_0ea7ef_idx'), models.Index(fields=['session', 'is_active'], name='attendance__session_aa49a4_idx')],
            },
        ),
    ]
