# Generated by Django 4.2.23 on 2025-10-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251025_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, default='', blank=True),
            preserve_default=False,
        ),
    ]
